### ISSUE TITLE
black window

### ISSUE THREAD

**Issue by ariaadhiguna99** [jmercouris/speech_recognition#2]
hi i tried to run the code but the only thing showing up is a black blank window. Do you know how to fix this? Thank you.
![kivysr](https://user-images.githubusercontent.com/48092923/70416866-996fa680-1a92-11ea-8f62-9d09d8a1320e.png)

**Comment by jmercouris** [comment]
Hi, thank you for your report. Are you able to run any of the Kivy demos? Does Kivy work on your machine?

**Comment by ariaadhiguna99** [comment]
I'm sorry it was a mistake on my part. I forgot to include the kv file, now I am able to run it. Thank you

**Comment by jmercouris** [comment]
No problem, I am glad to hear it is working for you :-)
